### ISSUE TITLE
AttributeError: 'Shell' object has no attribute 'dot'

### ISSUE THREAD

**Issue by Flimm** [seveas/dnsgraph#3]
I'm trying to run this command, and I'm getting this exception:

```
$ python tracegraph.py -t MX --graph png --output booking.png --skip . --skip com. booking.com
Trying to resolve booking.com. (MX) on a.root-servers.net. (198.41.0.4) (R:True)
Trying to resolve booking.com. (MX) on a.gtld-servers.net. (192.5.6.30) (R:True)
Trying to resolve booking.com. (MX) on ns0.bkngs.com. (5.57.23.169) (R:True)
# ....
Traceback (most recent call last):
  File "tracegraph.py", line 546, in <module>
    shell.dot(*args, input="\n".join(graph), stdout=sys.stdout)
  File "dnsgraph/env/lib/python2.7/site-packages/whelk/__init__.py", line 71, in __getattr__
    return self._getattr(name, defer=False)
  File "dnsgraph/env/lib/python2.7/site-packages/whelk/__init__.py", line 79, in _getattr
    return super(Shell, self).__getattribute__(name)
AttributeError: 'Shell' object has no attribute 'dot'
```

These are the libraries I have installed:

```
dnspython==1.15.0
whelk==2.7
```

**Comment by Wentao19** [comment]
Hi David, 

I run into exactly the same issue, have you fixed the issue?

Many thanks.

Regards,
Wentao

**Comment by seveas** [comment]
You'll need to install graphviz for this to work.

**Comment by Wentao19** [comment]
> You'll need to install graphviz for this to work.

Hi Dennis, 

Thanks for the heads up, after install graphviz, it works perfectly!

Thanks again for your help!

Regards,
Wentao

**Comment by Wentao19** [comment]
Hi Dennis,

Does the script support private domain?

Regards,
Wentao

**Comment by pabs3** [comment]
I have a patch that makes the error message more friendly, see #6.
